<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>dbseed</AssemblyName>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ApplicationIcon>dbseed.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="dbseed.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="6.*" />
  </ItemGroup>

</Project>
